### ISSUE TITLE
token account to sol account

### ISSUE THREAD

**Issue by simplewhale** [portto/solana-go-sdk#21]
I get the token account:"https://yihau.gitbook.io/solana-go/tour/create-token-account/associated-token-account".
And,how to use token account and mintPublickey backstepping the sol account?

**Comment by yihau** [comment]
if the token account has already initialized, you can get the token account's accountInfo and parse it as a token account to get the SOL account. You don't need the mintPublickey.

```go
package main

import (
	"context"
	"fmt"
	"log"

	"github.com/portto/solana-go-sdk/client"
	"github.com/portto/solana-go-sdk/client/rpc"
	"github.com/portto/solana-go-sdk/program/tokenprog"
)

func main() {
	c := client.NewClient(rpc.MainnetRPCEndpoint)
	accountInfo, err := c.GetAccountInfo(context.Background(), "your ATA address")
	if err != nil {
		log.Fatalf("failed to get account info, err: %v", err)
	}

	tokenAccount, err := tokenprog.TokenAccountFromData(accountInfo.Data)
	if err != nil {
		log.Fatalf("failed to parse token account, err: %v", err)
	}

	fmt.Printf("%+v\n", tokenAccount)
}

```

but if your token account hasn't initialized, I don't think you can use the token account and mint to get back the SOL address.
Even I don't how you get the token account, because the token account is derived by SOL address and mint pubkey.

**Comment by simplewhale** [comment]
okey,thank you
